version: '3.3'

services:
  application:
    container_name: heliopause
    image: roikiermedia/heliopause:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    # This section is for the treafik reverse proxy
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend=heliopause"
      - "traefik.frontend.rule=Host:api.chaostreff-flensburg.de"
      - "traefik.docker.network=web"
      - "traefik.port=80"
    environment:
      # Please change this token
      - TOKEN=42
    volumes:
      - ./data:/app/data
    restart: always

networks:
  web:
    external: true
